### ISSUE TITLE
The number of faces is 4x larger compared to vhacd in a test model

### ISSUE THREAD

**Issue by fy0** [SarahWeiii/CoACD#15]
out.glb is coacd result, 25 piceces, 1254 triangles
![image](https://github.com/SarahWeiii/CoACD/assets/1579850/c702a530-b5c2-4072-9ba1-7a9897817485)

code:
```python
import coacd
import trimesh
import numpy as np

input_file = './input.obj'
mesh = trimesh.load(input_file, force="mesh")
mesh = coacd.Mesh(mesh.vertices, mesh.faces)

parts = coacd.run_coacd(mesh, merge=True, threshold=0.05, resolution=2000, preprocess_resolution=50) # a list of convex hulls.

mesh_parts = []
for vs, fs in parts:
    mesh_parts.append(trimesh.Trimesh(vs, fs))

scene = trimesh.Scene()
np.random.seed(0)
for p in mesh_parts:
    p.visual.vertex_colors[:, :3] = (np.random.rand(3) * 255).astype(np.uint8)
    scene.add_geometry(p)

scene.export('./out.glb')
```

out2.glb is vhacd, 27 piceces, 374 triangles
![image](https://github.com/SarahWeiii/CoACD/assets/1579850/1367e3a7-b942-4a8f-90be-be3f41073edc)

code:
```python
import trimesh
import numpy as np

input_file = './input.obj'
mesh = trimesh.load(input_file, force="mesh")

parts = trimesh.interfaces.vhacd.convex_decomposition(mesh, maxhulls=10)

#print(parts)

#mesh_parts = []
#for vs, fs in parts:
#    mesh_parts.append(trimesh.Trimesh(vs, fs))

scene = trimesh.Scene()
np.random.seed(0)
for p in parts:
    p.visual.vertex_colors[:, :3] = (np.random.rand(3) * 255).astype(np.uint8)
    scene.add_geometry(p)

scene.export('./out2.glb')
```

source model:
![image](https://github.com/SarahWeiii/CoACD/assets/1579850/70e9026c-d71b-402c-80ca-3133b40ab873)

files:
[test.zip](https://github.com/SarahWeiii/CoACD/files/11541426/test.zip)

I feel like the triangles are mainly on the smooth edges. Is there a way to make the edges of the model sharper?

P.S. windows verison seems not work, tested on 2 computers, windows11 anaconda python 3.10.

**Comment by Lootheo** [comment]
I have this same issue, is there a way to not generate those smooth edges?

Also I cant seem to be able compile on windows.

**Comment by SarahWeiii** [comment]
The smooth edge problem is caused by mesh pre-processing, which turns a non-manifold mesh into manifold one, and it can introduce more triangles and smoothen the edges. 
You may disable the pre-process by adding `preprocess=False` to `run_coacd` and then the algorithm will keep the original shape as much as possible. Though using non-manifold mesh as input may have the risk of breaking the algorithm, it works in most cases in practice.

This is the result disbling pre-process with default parameters.
[17 pieces / 145 vertices / 222 faces]
![image](https://github.com/SarahWeiii/CoACD/assets/28781046/d49e0fa6-e044-44ac-b0a7-683d5b4e6d32)
[coacd_out.zip](https://github.com/SarahWeiii/CoACD/files/11628295/coacd_out.zip)

For the windows compiling problem, you may try installing `vc redist`
